import React, { useState } from 'react'
import { BsLinkedin,BsMailbox, BsMailbox2  } from 'react-icons/bs'
import pinterreach from './images/pinterreach.png'
import './App.css'
import { Nav } from './components/navigation/Nav'

import myImage from './images/myImage.png'
import scrapyard from './images/scraptest.png'
import pinter from './images/firstRep.png'
import friender from './images/friender.png'
import firstRep from './images/pinter.png'
import joseLema from './images/jose-lema.png'
import dualNBack from './images/dual-n-back.png'
import { Project } from './components/portfolio-pieces/Project'


function App() {
  const [darkMode,setDarkMode] = useState(false)
  const [color,setColor] = useState('white')
  const white = darkMode ? "dark" : "dark:text-white"

  return (
    <div>
    <head>
      <title>Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </head>
    <main className= {`space bg-white px-10 ${darkMode ? 'white' : 'dark'}:bg-gray-900 md:px-20 lg:px-40`}>
      <section className="min-h-screen">
        <Nav 
        color={color}
        darkMode={darkMode} 
        setDarkMode={()=>setDarkMode(!darkMode)} 
        // white={white}
        />
        <div className="text-center py-10">
          <h2 className={`text-5xl py-2 text-white font-medium dark:text-${color}-400 md:text-6xl`}>
            Rod Bromberg
          </h2>
          <h3 className={`text-2xl py-2 text-white md:text-4xl`}>
            Software Developer
          </h3>
         
          <p className={`text-xl py-5 leading-8 text-white max-w-xl mx-auto md:text-2xl`}>
            Frontend/Full-Stack Developer Open To New and Exciting Opportunities That Align With My Skillset 
            And Goals
          </p>
          <div className="text-5xl flex justify-center py-3 ">
            <a target="_blank" href="https://www.linkedin.com/in/rod-bromberg-590495175" rel="noopener noreferrer">
              <BsLinkedin className='text-white cursor-pointer mr-5'/>
            </a>

            <a href="mailto:rod.bromberg@yahoo.com, brombergrod@gmail.com">
              <BsMailbox className='text-white cursor-pointer'/>
            </a>
          </div>
        
          <div className={`my-image mx-auto bg-gradient-to-b rounded-full from-blue-400 to: to-blue-900 br-10 max-w-full w-80 relative overflow-hidden mt-20 md:h-96 md:w-96`}>
            <img className={`opacity-60`} src={myImage} alt="Rounded AI Generated Image Floating" />
          </div>
        </div>
      </section>
      <section>
          <h3 className={`text-4xl py-1 ${white}`}>About</h3>
        <div>
          <p className={`text-lg py-2 leading-8 white`}>
            Hi there, my name is Rod! Thanks for taking the time to visit my website. I have experience working remotely,
            but am also open to hybrid and onsite positions. Please feel free to contact me. 
            I've provided a link to my Linkedin, and Email above. If you would prefer to send me a text message 
            directly I have a form below that you may use to do so.
          </p>
        </div>
      </section>
      <section className="py-10">
        <div>
          <h3 className={`text-4xl py-1 ${white}`}>Portfolio</h3>
          <p className={`text-md py-2 leading-8 ${white}`}>
            
          </p>
          <p className={`text-md py-2 leading-8 text-gray-800 ${white}`}>
          
          </p>
        </div>
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">    
  <Project src={pinter} />
  <Project src={friender} />
  <Project src={joseLema} />
  <Project src={scrapyard} />
  <Project src={firstRep} />
  <Project src={dualNBack} />
</div>
      </section>
      <section className={`mb-10`}>
        {/* <h2 className={`text-${color} text-2xl mb-4`}>Contact</h2> */}
        {/* <Form /> */}
      </section>

    </main>

  </div>
  )
}

export default App