import React, { useState } from 'react'
import { BsLinkedin,  } from 'react-icons/bs'
import pinterreach from './images/pinterreach.png'
import './App.css'
import { Box } from './components/Box'
import { Nav } from './components/navigation/Nav'

import myImage from './images/myImage.png'
import scrapyard from './images/scraptest.png'
import pinter from './images/firstRep.png'
import friender from './images/friender.png'
import firstRep from './images/pinter.png'
import { Project } from './components/portfolio-pieces/Project'
import { Form } from './components/contact/Form'


function App() {
  const [darkMode,setDarkMode] = useState(false)
  const [color,setColor] = useState('white')
  const blackOrWhite = darkMode ? "dark" : "dark:text-white"

  return (
    <div>
    <head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </head>
    <main className= {`space bg-white px-10 ${darkMode ? 'white' : 'dark'}:bg-gray-900 md:px-20 lg:px-40`}>
      <section className="min-h-screen">
        <Nav 
        color={color}
        darkMode={darkMode} 
        setDarkMode={()=>setDarkMode(!darkMode)} 
        blackOrWhite={blackOrWhite}
        />
        <div className="text-center py-10">
          <h2 className={`text-5xl py-2 text-white font-medium dark:text-${color}-400 md:text-6xl`}>
            Rod Bromberg
          </h2>
          <h3 className={`text-2xl py-2 text-white md:text-3xl`}>
            Software Developer
          </h3>
          <p className={`text-xl py-5 leading-8 text-white max-w-xl mx-auto md:text-2xl`}>
            Frontend/Full-Stack Developer Open To New and Exciting Opportunities That Align With My Skillset and Goals
          </p>
          <div className="text-5xl flex justify-center py-3 ">
            <BsLinkedin className='text-white cursor-pointer'/>
          </div>
          <div className={`my-image mx-auto bg-gradient-to-b rounded-full from-blue-400 to: to-blue-900 br-10 max-w-full w-80 relative overflow-hidden mt-20 md:h-96 md:w-96`}>
            <img className={`opacity-60`} src={myImage} alt="Rounded AI Generated Image Floating" />
          </div>
        </div>
      </section>
      <section>
          <h3 className={`text-3xl py-1 ${blackOrWhite}`}>About Me</h3>
        <div>
          <p className={`text-md py-2 leading-8 ${blackOrWhite}`}>
            I've done remote work before but am also open to hybrid and onsite positions
          </p>
        </div>
      </section>
      <section className="py-10">
        <div>
          <h3 className={`text-3xl py-1 ${blackOrWhite}`}>Portofolio</h3>
          <p className={`text-md py-2 leading-8 ${blackOrWhite}`}>
            Since the beginning of my journey as a developer.
          </p>
          <p className={`text-md py-2 leading-8 text-gray-800 ${blackOrWhite}`}>
            I offer from a wide range of services, including brand design,
            programming and teaching.
          </p>
        </div>
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">    
          <Project src={pinter} />
          <Project src={friender} />
          <Project src={firstRep} />
          <Project src={scrapyard} />
        </div>
      </section>
      <section className={`mb-10`}>
        <h2 className={`text-${color} text-2xl `}>Contact Me</h2>
        <Form />
      </section>

    </main>

  </div>
  )
}

export default App